apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: my-project-01
  source:
    repoURL: https://github.com/muskenna/eks-argo-demo-app-source-code.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-web

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

# Doc: https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/
# Manifest example: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
